### PR TITLE
adding configuration do regression with latest Quarkus version

### PR DESCRIPTION
**Pull request by fmcejudo**

### CODE REVIEW

**Comment by fmcejudo** [comment]
@rsvoboda  @geoand just for you to take a look the  ECOSYSTEM_CI_REPO_PATH matches with folder in https://github.com/quarkusio/quarkus-ecosystem-ci.

**Comment by geoand** [comment]
Merged, thanks!

**Comment by fmcejudo** [comment]
@geoand thank you! really easy to do the process with the video and very well explained.

**Comment by geoand** [comment]
I'm glad you find it useful!

**Comment by geoand** [comment]
Can you please go to the `Actions` tab on your repository and check if actions are enabled? Asking because it seems like no action has been run.

**Comment by fmcejudo** [comment]
I have checked that and first option is enabled `Enable local and third party Actions for this repository`.
Might it be because of the scope of the token? it is just `repo`, does it need something else?

**Comment by geoand** [comment]
The token that you added based on the instructions should only need `repo` rights, but that shouldn't have anything to do with this. 
It seems that for some reason GH Actions isn't enabled at all on this repo...

Screenshot from 2020-04-27 14-52-50

**Comment by fmcejudo** [comment]
sorry, I think I spotted the issue, I had .github/`workflow` rather than .github/`workflows`.

I have pushed it yet, let's see if this triggers. Thanks @geoand

**Comment by geoand** [comment]
Nice catch, thanks @fmcejudo!

**Pull request merged**
